name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: luo-zn/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        # TARGET_REPO: zn-luo/zn-luo.github.io
        TARGET_BRANCH: master
        BUILD_SCRIPT: npm install && npm build
        BUILD_DIR: blog/.vuepress/dist