name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: testthedocs/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        # TARGET_REPO: zn-luo/zn-luo.github.io
        # TARGET_BRANCH: gh-pages
        BUILD_SCRIPT: npm install && npm run-script build
        BUILD_DIR: build/dist/