---
- name: Gather facts for all hosts
  hosts: all
  gather_facts: false
  tasks:
    - name: Gather facts
      setup:
  tags: always

- name: All nodes
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Distribution
      debug: msg="{{ ansible_distribution }}"

    - block:    
        - name: apt-key add download.docker.com gpg 
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

        - name: apt-key add download.docker.com gpg 
          apt_key:
            url: https://mirrors.aliyun.com/kubernetes/apt/doc/apt-key.gpg
            state: present

        - name: add download.docker.com
          raw: |
                cat <<EOF > /etc/apt/sources.list.d/docker-ce.list
                deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs)   stable 
                EOF
    
        - name: add k8s sources repos 
          raw: |
              cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
              deb https://mirrors.aliyun.com/kubernetes/apt kubernetes-xenial main
              EOF

        - name: Install docker-ce kubeadm kubectl kubelet in ubuntu
          apt:
            update_cache: yes
            pkg:
            - docker-ce=18.06.3~ce~3-0~ubuntu
            - kubeadm=1.11.1-00
            - kubernetes-cni=0.6.0-00
            - kubelet=1.11.1-00
      when:
        - ansible_distribution == "Ubuntu"

- name: Master nodes
  hosts: master
  gather_facts: False
  become: true
  tasks:
    - block:
        - name: Install kubectl=1.11.1-00
          apt:
            name: kubectl=1.11.1-00
            state: present
      when:
        - ansible_distribution == "Ubuntu"

- name: Node(Worker) nodes
  hosts: node
  gather_facts: False
  become: true
  tasks:
    - name: Get os release  info
      raw: cat /etc/os-release
      register: os_release
